# This is an example action that computes the Fibonacci sequence up to a
# given order. It is provided to demonstrate and test action interfaces;
# a semantically meaningful one should be created to be built upon.

# Goal
int32 order
---
# Result
int32[] sequence
---
# Feedback
int32[] sequence
