blank_issues_enabled: false
contact_links:
  - name: robotsix-mill Discussions
    url: https://github.com/robotsix/mill/discussions
    about: Please ask general questions and start discussions here.
